In [2]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d

# 6. 고유공간과 대각화

## 1) 대각화

### (1) 대각화는 다음의 경우에 활용할 수 있다.

 - 선형계의 발산의 판단 : 행렬A를 대각화 하는 경우, 대각행렬의 요소값을 통해 발산 여부를 판단할 수 있다.(|a| > 1이면 발산한다)
 - 연산의 최적화 : 행렬 A를 연속적으로 적용하는 변환의 경우, 대각화 할 경우 대각행렬만 계속 곱해주면 A를 연속 적용하는것과 같다.

### (2) 발산 판단 여부의 판단

### - 대각행렬의 경우

In [3]:
A = np.diag([5,-3,0.8])
x = np.array(["X_1,X_2,X_3"])

- A와 x를 내적하면

In [4]:
Ax = np.matrix(["5 * x_1", "-3 * x_2", "0.8 * x_3"])
print(Ax.T)

[['5 * x_1']
 ['-3 * x_2']
 ['0.8 * x_3']]


- 꼴로 나타난다. 따라서, 차분방정식을 이용할경우 파라미터 A의 t제곱(t = infinity)에서 안정된 값이 구해지는데

In [5]:
A ** np.inf

array([[inf,  0.,  0.],
       [ 0., inf,  0.],
       [ 0.,  0.,  0.]])

### 이 대각행렬은 a33 성분을 제외하고는 무한으로 발산하므로, 이 시스템은 t = infinity일때 발산한다.

### - 대각행렬은 아니지만, 대각화가 가능한 경우

In [6]:
A = np.matrix([[5,1],[1,5]])
x_1 = np.array(["x1_1","x2_1"]) #단, x1_1은 변수 x1의 1차시 전 값을, x2_1은 변수 x2의 1차시 전 값을 의미한다. 

- 이 때, 이 행렬의 곱은

In [7]:
print(np.matrix([["X1","X2"]]))
print("=")
print(A)
print("*")
print(x_1)
print("=")
print(np.matrix([["(5 * x1_1) + (x2_1)"],["(x1_1) + (5 * x2_1)"]]))

[['X1' 'X2']]
=
[[5 1]
 [1 5]]
*
['x1_1' 'x2_1']
=
[['(5 * x1_1) + (x2_1)']
 ['(x1_1) + (5 * x2_1)']]


 - 변수변환을 다음과 같이 실시한다.
 - y1 = x1 + x2
 - y2 = x1 - x2

In [8]:
C = np.matrix([[1,1],[1,-1]])
x = np.array(["X1,X2"]) #단, X1, X2는 변수 X1, X2의 현상태의 값을 의미한다.

Cx = np.matrix([["X1 + X2"],["X1 - X2"]])

In [9]:
print(np.matrix([["y1"],["y2"]]),"\n = \n", Cx)

[['y1']
 ['y2']] 
 = 
 [['X1 + X2']
 ['X1 - X2']]


- 변수변환과 원래 행렬을 동시에 정의하면

In [10]:
print(np.matrix([["y1"],["y2"]]))
print("=")
print(A,"\n * \n",C,"\n * \n",x_1)

[['y1']
 ['y2']]
=
[[5 1]
 [1 5]] 
 * 
 [[ 1  1]
 [ 1 -1]] 
 * 
 ['x1_1' 'x2_1']


- 한편, 우변을 하나로 정리해주면

In [11]:
print(np.matrix([["5 * X1_1 + X2_1 + X1_1 + 5 * X2_1"],["5 * X1_1 + X2_1 - X1_1 - 5 * X2_1"]]))
print("=")
print(np.matrix([["6X1 + 6X2"],["4X1 - 4X2"]]))

[['5 * X1_1 + X2_1 + X1_1 + 5 * X2_1']
 ['5 * X1_1 + X2_1 - X1_1 - 5 * X2_1']]
=
[['6X1 + 6X2']
 ['4X1 - 4X2']]


 - 위 식을 다시 행렬꼴로 나타내면

In [12]:
K = np.matrix([[6,0],[0,4]])
print(np.matrix([["y1"],["y2"]]))
print("=")
print(np.matrix([["6X1 + 6X2"],["4X1 - 4X2"]]))
print("=")
print(K)
print("*")
print(C)
print("*")
print(x_1)

[['y1']
 ['y2']]
=
[['6X1 + 6X2']
 ['4X1 - 4X2']]
=
[[6 0]
 [0 4]]
*
[[ 1  1]
 [ 1 -1]]
*
['x1_1' 'x2_1']


- 이 때, 대각행렬은 차분방정식에서 t = infinity일때 안정화되므로, 이 계는 궁극적으로 발산한다.

In [13]:
# - 한편
print(np.matrix([["y1"],["y2"]]))
print("=")
print(C)
print("*")
print(x)
# 이므로

[['y1']
 ['y2']]
=
[[ 1  1]
 [ 1 -1]]
*
['X1,X2']


In [14]:
print("C행렬의 역 : \n",np.linalg.inv(C)) #을 이용하여 표현하면
print("\n")
print(x)
print("=")
print(np.linalg.inv(C))
print("*")
print(np.matrix([["y1"],["y2"]]))

#이다.

C행렬의 역 : 
 [[ 0.5  0.5]
 [ 0.5 -0.5]]


['X1,X2']
=
[[ 0.5  0.5]
 [ 0.5 -0.5]]
*
[['y1']
 ['y2']]


In [15]:
# 앞서 

print(np.matrix([["y1"],["y2"]]))
print("=")
print(C)
print("*")
print(x)
# 이므로, 이를 앞에서 구한 역행렬과 내적하면

[['y1']
 ['y2']]
=
[[ 1  1]
 [ 1 -1]]
*
['X1,X2']


In [16]:
print(x)
print("=")
print(np.linalg.inv(C))
print("*")
print(K)
print("*")
print(C)
print("*")
print(x_1)

['X1,X2']
=
[[ 0.5  0.5]
 [ 0.5 -0.5]]
*
[[6 0]
 [0 4]]
*
[[ 1  1]
 [ 1 -1]]
*
['x1_1' 'x2_1']


- 이 때, C와 C^-1 사이에 대각행렬 diag(6,4)가 끼어있는 형태가 나오고, 이 형식을 맨 처음에 언급한

In [17]:
print(np.matrix([["X1","X2"]]))
print("=")
print(A)
print("*")
print(x_1)

#와 비교하면

[['X1' 'X2']]
=
[[5 1]
 [1 5]]
*
['x1_1' 'x2_1']


In [18]:
print(A)
print("=")
print(np.linalg.inv(C))
print("*")
print(K)
print("*")
print(C)

#임이 명백하다.

[[5 1]
 [1 5]]
=
[[ 0.5  0.5]
 [ 0.5 -0.5]]
*
[[6 0]
 [0 4]]
*
[[ 1  1]
 [ 1 -1]]


- A = inv(C) * diag(ㅅ) * C 꼴로 분해하였는데, 이 것을 대각화라고 한다.
- 이제 관건은, 앞서 대각화를 가능하게 했던 행렬

In [19]:
print(C)

#를 찾는 것이다.

[[ 1  1]
 [ 1 -1]]


## 2) 고윳값과 고유벡터

### (1) 고유벡터의 기하학적 이해

### (2) 고윳값과 고유벡터의 도출

### - 특성방정식

 - 어떤 행렬이 특이행렬이 되도록 만들어주는 고윳값을 구하는 방정식
 - 즉, det(A - aI) = 0이 되도록 하는 a를 구한다.

In [40]:
A = np.matrix([[6,-3,5],[-1,4,-5],[-3,3,-4]])

- 3X3 행렬이므로, 사루스의 법칙을 이용하여 행렬식을 구하면

det(A - aI) = {(6-a)(4-a)(-4-a)]} + {-3 * -5 * -3}  + {5 * -1 * 3} - {5 * (4-a) * -3} - {(6-a) * -5 * 3} - {-3 * -1 * (4-a)} = a^3-6a^2+11a-6
- 이 때 해는

In [41]:
a = np.matrix([3,2,1])
print(a)

[[3 2 1]]


이다

- 이제 고윳값에 맞는 고유벡터를 구하면
- 각 고윳값을 대각성분에서 뺀 행렬의 영공간을 구한다.

In [60]:
A_eig_1 = (A - a[0,0] * np.identity(3))
print(A_eig_1)

[[ 3. -3.  5.]
 [-1.  1. -5.]
 [-3.  3. -7.]]


이 행렬을 행연산하면 다음과 같은 행렬이 된다.

In [81]:
A_eig_1_reduced = np.matrix([[1,-1,0],[0,0,1],[0,0,0]])
print(A_eig_1_reduced)

[[ 1 -1  0]
 [ 0  0  1]
 [ 0  0  0]]


위 행줄임 행렬을 영공간의 Span으로 나타내면


In [82]:
print(np.matrix(["x1","x2","x3"]).T)
print("=")
print(np.matrix([1,1,0]).T)
print("*")
print("x2")
print("단, x2는 0 이외의 모든 실수이다.")

[['x1']
 ['x2']
 ['x3']]
=
[[1]
 [1]
 [0]]
*
x2
단, x2는 0 이외의 모든 실수이다.


In [73]:
A_eig_2 = (A - a[0,1] * np.identity(3))
print(A_eig_2)

[[ 4. -3.  5.]
 [-1.  2. -5.]
 [-3.  3. -6.]]


이 행렬을 행연산하면 다음과 같은 행렬이 된다.

In [76]:
A_eig_2_reduced = np.matrix([[1,0,-1],[0,1,-3],[0,0,0]])
print(A_eig_2_reduced)

[[ 1  0 -1]
 [ 0  1 -3]
 [ 0  0  0]]


위 행줄임 행렬을 영공간의 Span으로 나타내면

In [79]:
print(np.matrix(["x1","x2","x3"]).T)
print("=")
print(np.matrix([1,3,1]).T)
print("*")
print("x3")
print("단, x3는 0 이외의 모든 실수이다.")

[['x1']
 ['x2']
 ['x3']]
=
[[1]
 [3]
 [1]]
*
x3
단, x3는 0 이외의 모든 실수이다.


In [85]:
A_eig_3 = (A - a[0,2] * np.identity(3))
print(A_eig_3)

[[ 5. -3.  5.]
 [-1.  3. -5.]
 [-3.  3. -5.]]


이 행렬을 행연산하면 다음과 같은 행렬이 된다.

In [88]:
A_eig_3_reduced = np.matrix([[1,0,0],[0,1,(-5/3)],[0,0,0]])
print(A_eig_3_reduced)

[[ 1.          0.          0.        ]
 [ 0.          1.         -1.66666667]
 [ 0.          0.          0.        ]]


위 행줄임 행렬을 영공간의 Span으로 나타내면

In [90]:
print(np.matrix(["x1","x2","x3"]).T)
print("=")
print(np.matrix([0,5,3]).T)
print("*")
print("x3")
print("단, x3는 0 이외의 모든 실수이다.")

[['x1']
 ['x2']
 ['x3']]
=
[[0]
 [5]
 [3]]
*
x3
단, x3는 0 이외의 모든 실수이다.


In [99]:
eigen_value = np.diag([3,2,1])
eigen_vector = np.matrix([[1,1,0],[1,3,1],[0,5,3]]).T

In [100]:
eigen_value

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 1]])

In [109]:
eigen_vector

matrix([[1, 1, 0],
        [1, 3, 5],
        [0, 1, 3]])

이다

# 3) 총 정리 예제

### (1) 어떤 자기회귀(AR)모델이 다음과 같이 정의되었다.
 - y(t) = -0.5y(t-1) + 0.34y(t-2) + 0.08y(t-3) + 2u(t)
 - 초기조건 y(0) = 0.78, y(-1) = 0.8, y(-2) = 1.5

In [90]:
def init_x(t):
    if t == 0:
        y_1 = 0.8
        y_2 = 1.5
        y_3 = (0.78+0.5*(0.8) - 0.34*(1.5))/0.08
        return ([y_1,y_2,y_3])

In [91]:
A = np.matrix([[-0.5,0.34,0.08],[1,0,0],[0,1,0]])
x = np.matrix(init_x(0)).T
print(A)

[[-0.5   0.34  0.08]
 [ 1.    0.    0.  ]
 [ 0.    1.    0.  ]]


- 위 방정식의 경우, A와 x를 내적하면 

In [92]:
np.dot(A,x) # 이것이 t=0일때의 초깃값 y_1, y_2, y_3이다.

matrix([[0.78],
        [0.8 ],
        [1.5 ]])

In [98]:
# 행렬 A를 고유분해하면

A_eig = np.linalg.eig(A)
print("행렬 A의 고윳값 : ","\n",A_eig[0])
print("행렬 A의 고유벡터 : ","\n",A_eig[1])

행렬 A의 고윳값 :  
 [-0.8  0.5 -0.2]
행렬 A의 고유벡터 :  
 [[-0.447039   -0.21821789  0.03919309]
 [ 0.55879876 -0.43643578 -0.19596545]
 [-0.69849845 -0.87287156  0.97982725]]


In [117]:
#이 계의 고윳값 대각행렬의 안정값은
np.diag(A_eig[0]) ** np.inf

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [118]:
# 이므로, 모두 0이기 때문에 궁극적으로 발산하지 않고 수렴한다.